
name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:

  run-tests:
#    runs-on: ubuntu-latest
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Run Test Action
        uses: ./.github/actions/go-test

  build:
    needs: [run-tests]
#    runs-on: ubuntu-latest
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: tag name
        run: echo "${{github.ref_name}}"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Get go mod dependencies
        run: go mod download

      - name: Build
        run: go build -mod=mod -v -o LC-ModUtility_${{github.ref_name}}.exe ./cmd/LC-ModUtility/lethalModUtility.go

      - name: list
        run: ls

#  publish:
#    needs: [build]
##    runs-on: ubuntu-latest
#    runs-on: windows-2022
#    permissions:
#      contents: write
#    steps:
#      - uses: actions/checkout@v4
#      - uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            LC-ModUtility_${{github.ref_name}}.exe
#            Update-Lethal-Company-Modpack.bat
