
name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:

  run-tests:
#    runs-on: ubuntu-latest
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Run Test Action
        uses: ./.github/actions/go-test

  build:
    needs: [run-tests]
#    runs-on: ubuntu-latest
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: tag name
        run: echo "${{github.ref_name}}"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Get go mod dependencies
        run: go mod download

      - name: Build
        run: go build -mod=mod -v -o LC-ModUtility_${{github.ref_name}}.exe ./cmd/LC-ModUtility/lethalModUtility.go

      - name: list
        run: ls

      - name: Upload exe artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe-file
          path: LC-ModUtility_${{github.ref_name}}.exe

  publish:
    needs: [build]
#    runs-on: ubuntu-latest
    runs-on: windows-2022
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download exe artifact
        uses: actions/download-artifact@v3
        with:
          name: exe-file

      - name: list
        run: ls

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            LC-ModUtility_${{github.ref_name}}.exe
            Update-Lethal-Company-Modpack.bat
