# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  run-tests:
#    runs-on: ubuntu-latest
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Run Test Action
        uses: ./.github/actions/go-test
